# Generated by Django 5.2.2 on 2025-07-04 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=200)),
                ('subheadline', models.TextField()),
                ('stat_positions', models.CharField(max_length=100)),
                ('stat_companies', models.CharField(max_length=100)),
                ('stat_success', models.CharField(max_length=100)),
                ('stat_salary', models.CharField(max_length=100)),
                ('why_choose_us_title', models.CharField(default='Why Choose Us?', max_length=100)),
                ('feature_1_title', models.CharField(max_length=100)),
                ('feature_1_description', models.TextField()),
                ('feature_2_title', models.CharField(max_length=100)),
                ('feature_2_description', models.TextField()),
                ('feature_3_title', models.CharField(max_length=100)),
                ('feature_3_description', models.TextField()),
                ('feature_4_title', models.CharField(max_length=100)),
                ('feature_4_description', models.TextField()),
                ('cta_title', models.CharField(max_length=200)),
                ('cta_description', models.TextField()),
            ],
        ),
    ]
