# Generated by Django 5.2.2 on 2025-07-04 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=300, null=True)),
                ('who_we_are', models.TextField()),
                ('vision', models.TextField()),
                ('mission', models.TextField()),
                ('core_values', models.TextField()),
            ],
        ),
    ]
