# Generated by Django 5.2.2 on 2025-07-04 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_job_job_type_alter_job_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdetails',
            name='benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='job_type',
            field=models.CharField(default='Full-time', max_length=50),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobdetails',
            name='responsibilities',
            field=models.TextField(blank=True),
        ),
    ]
