# Generated by Django 5.2.2 on 2025-07-04 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_jobdetails_benefits_alter_jobdetails_job_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='app.jobdetails'),
        ),
    ]
