# Generated by Django 5.2.2 on 2025-07-04 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_jobapplication_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('section_1_title', models.CharField(max_length=100)),
                ('section_1_body', models.TextField()),
                ('section_2_title', models.CharField(max_length=100)),
                ('section_2_body', models.TextField()),
                ('core_values', models.TextField(help_text='Separate values with commas')),
            ],
        ),
    ]
