# Generated by Django 5.2.2 on 2025-07-04 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_aboutcontent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='address',
            new_name='cover_letter',
        ),
    ]
